# Generated by Django 5.0 on 2023-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_text",
            field=models.TextField(default=""),
        ),
    ]
