# Generated by Django 5.0 on 2023-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_meta_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="meta_text",
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(
                default="This is the description of the blog", max_length=255
            ),
            preserve_default=False,
        ),
    ]
